### ISSUE TITLE
Only seems to work when running as an administrator

### ISSUE THREAD

**Issue by chrisoldwood** [TinyBlueRobots/Hornbill#6]
When I run my tests, irrespective of whether I pick a low or high-numbered port (or let `FakeServer` pick one), I always get an access denied error when calling `Start()`. It seems the only way to make it work is to be developing as an administrator, which is a practice I gave up well over a decade ago :o).

This is the error I get when calling the method:

```
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.Net.HttpListenerException : Access is denied
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Hornbill.FakeService.Start() in C:\dev\Hornbill\src\Hornbill\FakeService.fs:line 74
   . . . 
--HttpListenerException
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
```

So how do I use Hornbill with a LUA style account? Thanks.

**Comment by chrisoldwood** [comment]
I'm running on Windows 10 and I know Microsoft changed the rules so that listening on a `localhost` only port was allowed, which is what this comment on the SO page suggests:

http://stackoverflow.com/questions/4019466/httplistener-access-denied#comment58025168_18786486

Looking at your code, I think the problem is that the code is listening on `*` instead of just `localhost`:

```
let createHost =
      fun name -> sprintf "http://%s:%i" name port
    url <- createHost "localhost"
    webApp <- WebApp.Start(createHost "*", Middleware.app requests.Add findResponse setResponse requestReceived.Trigger)
    url
```

i.e. `WebApp.Start(createHost "*"` should be `WebApp.Start(createHost "localhost"` perhaps?

If so would it make sense to allow both the listening host _and_ port number to be specified so that it can be safely run as a non-administrator. Maybe this should be the default behaviour as I personally think it's unusual to run automated tests with a real network in the path [1].

[1] I've certainly done it when running acceptance tests but that usually makes the CI test run more like a proper deployment rather than running the tests in-process.

**Comment by JonCanning** [comment]
If you change it and run the build does it work?

**Comment by chrisoldwood** [comment]
So I've just managed to try it out (it's the first F# I've written in 7 years :o) ) and all the Hornbill tests now run & pass as an non-admin:

```
webApp <- WebApp.Start(createHost "localhost", Middleware.app requests.Add findResponse setResponse requestReceived.Trigger)
```

**Comment by JonCanning** [comment]
Good stuff, submit a PR!

**Comment by chrisoldwood** [comment]
That only fixes it by hacking it, I don't know what you want to do about making this the default or optional behaviour?

**Comment by JonCanning** [comment]
1.5.3 released
